name: DvZ
version: 1.0.0
main: main.me.volt.dvz.DvZ
api-version: 1.14
depend: [ MagicSpells, MCEvolved ]

commands:
  startgame:
    description: Starts the game.
    permission: dvz.admin
  override:
    description: Allows admin to control the game.
    permission: dvz.admin
  event:
    description: Allows admin to start event.
    permission: dvz.admin
  warpshrine:
    description: Warp to current dwarf shrine.
    permissions: dvz.admin
  releasemonsters:
    description: Releases the monsters.
    permission: dvz.admin
  setdwarf:
    description: Set a player as a dwarf.
    permission: dvz.admin
  setmonster:
    description: Set a player as a monster.
    permission: dvz.admin
  sethero:
    description: Set a player as a hero.
    permission: dvz.admin
    aliases: [sethero, hero, heroset]
  specialmonsterinterval:
    description: Sets the special monster interval.
    permission: dvz.admin
    aliases: [monsterspecialinterval, specialmonster, monsterspecial]

permissions:
  dvz.admin:
    description: Permissions for admin commands.
    default: op
  game.ignore:
    description: Ignores the player for the game.
    default: false
  dvz.nojoindeath:
    description: Makes the player able to rejoin without dying.
    default: false
  dvz.immune:
    description: Makes the player immune to the plague.
    default: false